replicaCount: 2

image:
  repository: 659591640509.dkr.ecr.us-west-2.amazonaws.com/streamlinepay-prod-cart-cna-microservice
  tag: bb2504e-116
  pullPolicy: IfNotPresent

# ADD THIS: Link to the secret you will create via kubectl
imagePullSecrets:
  - name: ecr-private-key

service:
  type: ClusterIP
  port: 8081

# ... (rest of your existing values)