replicaCount: 2

image:
  repository: 659591640509.dkr.ecr.us-west-2.amazonaws.com/streamlinepay-prod-cart-cna-microservice
  tag: bb2504e-116
  pullPolicy: IfNotPresent

imagePullSecrets:
  - name: ecr-private-key

service:
  type: ClusterIP
  port: 8081

# FIXED: Ensure this section exists and is properly indented
serviceAccount:
  create: true
  name: "cart-sa"
  automount: true

cartSecret:
  name: "cart-chart-secret"
  redisKey: "redisUri"
  jwtKey: "jwtSecret"

configMap:
  API_BASE_URL: "http://product-service.default.svc.cluster.local:8080"
  FEATURE_FLAG: "true"