apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "user.fullname" . }}-config
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "user.labels" . | nindent 4 }}
data:
  FEATURE_FLAG: {{ .Values.configMap.FEATURE_FLAG | quote }}
  LOG_LEVEL: {{ .Values.configMap.LOG_LEVEL | quote }}