apiVersion: v1
kind: Secret
metadata:
  name: user-chart-secret
  namespace: user
type: Opaque
stringData:
  dbUri: mongodb://useradmin:userpass@mongodb.database.svc.cluster.local:27017/users
  jwtSecret: supersecretjwtkey
