apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.userSecret.name }}
  namespace: {{ .Release.Namespace }}
type: Opaque
data:
  {{ .Values.userSecret.dbUriKey }}: {{ .Values.userConfig.dbUri | b64enc }}
  {{ .Values.userSecret.jwtKey }}: {{ .Values.userConfig.jwtSecret | b64enc }}
