apiVersion: v1
kind: Secret
metadata:
  name: {{ include "user.fullname" . }}-secret
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "user.labels" . | nindent 4 }}
type: Opaque
stringData:
  dbUri: {{ .Values.userConfig.dbUri | quote }}
  jwtSecret: {{ .Values.userConfig.jwtSecret | quote }}
