apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.userSecret.name }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "user.labels" . | nindent 4 }}
type: Opaque
stringData:
  dbUri: {{ .Values.userSecret.dbUri | quote }}
  jwtSecret: {{ .Values.userSecret.jwtSecret | quote }}