replicaCount: 2

image:
  repository: 659591640509.dkr.ecr.us-west-2.amazonaws.com/streamlinepay-prod-user-cna-microservice
  tag: bb2504e-116
  pullPolicy: IfNotPresent

service:
  type: ClusterIP
  port: 3002

userSecret:
  name: "user-service-secret"
  dbUri: "mongodb://useradmin:userpass@mongodb.database.svc.cluster.local:27017/users"
  jwtSecret: "supersecretjwtkey"

serviceAccount:
  create: true
  name: "users-sa"
  automount: true

autoscaling:
  enabled: true
  minReplicas: 1
  maxReplicas: 5
  targetCPUUtilizationPercentage: 70

configMap:
  FEATURE_FLAG: "true"
  LOG_LEVEL: "info"