replicaCount: 2

image:
  repository: your-docker-registry/product-catalog-ms
  tag: "1.0.0"
  pullPolicy: IfNotPresent

config:
  mongoDbUri: "mongodb://mongo-clusterip:27017/productsdb"

resources:
  limits:
    cpu: 300m
    memory: 256Mi
  requests:
    cpu: 100m
    memory: 128Mi

service:
  type: ClusterIP
  port: 80
  nodePort: null
  labels:
    app.kubernetes.io/component: backend
    app.kubernetes.io/part-of: e-commerce
  annotations: {}

serviceAccount:
  create: true
  name: ""
