replicaCount: 2

image:
  repository: 659591640509.dkr.ecr.us-west-2.amazonaws.com/streamlinepay-prod-products-cna-microservice
  tag: bb2504e-116
  pullPolicy: IfNotPresent

service:
  type: ClusterIP
  port: 3001

resources:
  requests:
    cpu: "250m"
    memory: "256Mi"
  limits:
    cpu: "500m"
    memory: "512Mi"

securityContext:
  runAsUser: 1001
  runAsGroup: 1001
  fsGroup: 1001

productsSecret:
  name: "products-chart-secret"
  dbUriKey: "dbUri"
  jwtKey: "jwtSecret"

serviceAccount:
  create: true
  # REQUIRED: This must match what is in your Deployment's serviceAccountName field
  name: "products-chart-sa"
  automount: true

configMap:
  FEATURE_FLAG: "true"
  LOG_LEVEL: "debug"

autoscaling:
  enabled: true
  minReplicas: 1
  maxReplicas: 3
  targetCPUUtilizationPercentage: 70