replicaCount: 2

image:
  repository: streamlinpay-prod-products-cna-microservice
  tag: bb2504e-116
  pullPolicy: IfNotPresent

service:
  type: ClusterIP
  port: 3001

resources:
  requests:
    memory: "256Mi"
    cpu: "250m"
  limits:
    memory: "512Mi"
    cpu: "500m"

securityContext:
  runAsUser: 1001
  runAsGroup: 1001
  fsGroup: 1001

productsSecret:
  name: "products-chart-secret" 
  dbUriKey: "POSTGRES_URI"
  jwtKey: "JWT_SECRET" 

config:
  mongoDbUri: mongodb://mongoadmin:mongodb123@mongodb.database.svc.cluster.local:27017/products

autoscaling:
  enabled: true
  minReplicas: 1
  maxReplicas: 3
  targetCPUUtilizationPercentage: 70

serviceAccount:
  name: products-chart-sa

configMap:
  FEATURE_FLAG: "true"
  LOG_LEVEL: "debug"