apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.mongodbSecret.name }}
  namespace: database
type: Opaque
data:
  {{ .Values.mongodbSecret.usernameKey }}: {{ .Values.mongodb.username | b64enc }}
  {{ .Values.mongodbSecret.passwordKey }}: {{ .Values.mongodb.password | b64enc }}
