apiVersion: v1
kind: ConfigMap
metadata:
  name: products-config-map
  labels:
    {{- include "products.labels" . | nindent 4 }}
data:
  FEATURE_FLAG: {{ .Values.configMap.FEATURE_FLAG | quote }}
  LOG_LEVEL: {{ .Values.configMap.LOG_LEVEL | quote }