apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "products.fullname" . }}
  labels:
    {{- include "products.labels" . | nindent 4 }}
spec:
  {{- if not .Values.autoscaling.enabled }}
  replicas: {{ .Values.replicaCount }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "products.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "products.selectorLabels" . | nindent 8 }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "products.serviceAccountName" . }}
      containers:
        - name: product-catalog
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          command: ["/nodejs/bin/node"]
          args: ["server.js"]
          ports:
            - name: http
              containerPort: 3001
              protocol: TCP

          readinessProbe:
            httpGet:
              path: /health
              port: 3001
            initialDelaySeconds: 10
            periodSeconds: 10
            failureThreshold: 3

          livenessProbe:
            httpGet:
              path: /health
              port: 3001
            initialDelaySeconds: 20
            periodSeconds: 15
            failureThreshold: 5

          env:
            - name: POSTGRES_URI
              valueFrom:
                secretKeyRef:
                  name: products-config-secret
                  key: dbUri
            - name: JWT_SECRET
              valueFrom:
                secretKeyRef:
                  name: products-config-secret
                  key: jwtSecret

          envFrom:
            - configMapRef:
                name: products-config-map

          resources:
            {{- toYaml .Values.resources | nindent 12 }}
