apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "products.fullname" . }}
  labels:
    {{- include "products.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "products.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "products.selectorLabels" . | nindent 8 }}
    spec:
      serviceAccountName: {{ .Values.serviceAccount.name }}
      containers:
        - name: products
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}

          ports:
            - name: http
              containerPort: 3001

          env:
            - name: POSTGRES_URI
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.productsSecret.name }}
                  key: dbUri
            - name: JWT_SECRET
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.productsSecret.name }}
                  key: jwtSecret

          envFrom:
            - configMapRef:
                name: {{ include "products.fullname" . }}-config

          readinessProbe:
            httpGet:
              path: /health
              port: http
            initialDelaySeconds: 5
            periodSeconds: 10

          livenessProbe:
            httpGet:
              path: /health
              port: http
            initialDelaySeconds: 15
            periodSeconds: 20

          resources:
            {{- toYaml .Values.resources | nindent 12 }}
