apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "products.fullname" . }}
  labels:
    {{- include "products.labels" . | nindent 4 }}
spec:
  revisionHistoryLimit: 3
  {{- if not .Values.autoscaling.enabled }}
  replicas: {{ .Values.replicaCount }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "products.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "products.selectorLabels" . | nindent 8 }}
    spec:
      containers:
        - name: product-catalog
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          
          # ðŸŸ¢ Fix: Execute via shell to find node path and run server.js
          command: ["/bin/sh", "-c"]
          args: ["node server.js"]

          ports:
            - name: http
              containerPort: 3001
              protocol: TCP

          readinessProbe:
            httpGet:
              path: {{ .Values.probes.readinessPath }}
              port: http
            initialDelaySeconds: 15
            periodSeconds: 10

          livenessProbe:
            httpGet:
              path: {{ .Values.probes.livenessPath }}
              port: http
            initialDelaySeconds: 30
            periodSeconds: 20

          env:
            - name: POSTGRES_URI
              valueFrom:
                secretKeyRef:
                  name: products-config-secret
                  key: dbUri
            - name: JWT_SECRET
              valueFrom:
                secretKeyRef:
                  name: products-config-secret
                  key: jwtSecret
          envFrom:
            - configMapRef:
                name: products-config-map
          resources:
            {{- toYaml .Values.resources | nindent 12 }}