apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "products.fullname" . }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "products.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "products.selectorLabels" . | nindent 8 }}
    spec:
      containers:
        - name: product-catalog
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          command: ["/nodejs/bin/node"]
          workingDir: /app
          args: ["index.js"] # Clean path thanks to your Dockerfile fix!
          ports:
            - containerPort: 3001
          env:
            - name: POSTGRES_URI
              valueFrom:
                secretKeyRef:
                  name: products-chart-secret 
                  key: dbUri
          envFrom:
            - configMapRef:
                name: products-config