apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "products.fullname" . }}
  labels:
    {{- include "products.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "products.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "products.selectorLabels" . | nindent 8 }}
    spec:
      serviceAccountName: {{ .Values.serviceAccount.name }}
      containers:
        - name: product-catalog
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          
          # FIX: Mandatory for Distroless
          command: ["/nodejs/bin/node"]
          workingDir: /app
          args: ["server.js"] 

          ports:
            - name: http
              containerPort: 3001
              protocol: TCP

          env:
            - name: POSTGRES_URI
              valueFrom:
                secretKeyRef:
                  name: products-config-secret
                  key: dbUri
            - name: JWT_SECRET
              valueFrom:
                secretKeyRef:
                  name: products-config-secret
                  key: jwtSecret

          envFrom:
            - configMapRef:
                name: products-config-map

          readinessProbe:
            httpGet:
              path: /health
              port: 3001
            initialDelaySeconds: 10
            periodSeconds: 10

          resources:
            {{- toYaml .Values.resources | nindent 12 }}