{{- if .Values.autoscaling.enabled }}
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: {{ include "products.fullname" . }}
  labels:
    {{- include "products.labels" . | nindent 4 }}
spec:
...
{{- end }}