apiVersion: v1
kind: Secret
metadata:
  name: products-config-secret
  labels:
    {{- include "products.labels" . | nindent 4 }}
type: Opaque
stringData:
  # This pulls from the values.yaml we are about to update
  dbUri: {{ .Values.productsSecret.dbUri | quote }}
  jwtSecret: {{ .Values.productsSecret.jwtSecret | quote }}
  