apiVersion: v1
kind: Secret
metadata:
  name: products-chart-secret
  type: Opaque
stringData:
  dbUri: postgres://productadmin:productpass@postgresql.database.svc.cluster.local:5432/products
  jwtSecret: supersecretjwtkey
