apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.productsSecret.name }}
  labels:
    {{- include "products.labels" . | nindent 4 }}
type: Opaque
stringData:
  dbUri: {{ .Values.productsSecret.dbUri | quote }}
  jwtSecret: {{ .Values.productsSecret.jwtSecret | quote }}
