apiVersion: v1
kind: Service
metadata:
  name: {{ include "products.fullname" . }}
  labels:
    {{- include "products.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - name: http
      port: {{ .Values.service.port }}
      targetPort: 3001  # âœ… Matches containerPort in deployment.yaml
      protocol: TCP
  selector:
    {{- include "products.selectorLabels" . | nindent 4 }}