apiVersion: v1
kind: Service
metadata:
  name: {{ include "products.fullname" . }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - name: http
      port: 80          # ðŸ‘ˆ Change this from {{ .Values.service.port }} to 80
      targetPort: 3001  # This stays 3001 to match your app
      protocol: TCP
  selector:
    {{- include "products.selectorLabels" . | nindent 4 }}