apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "products-chart.fullname" . }}-sa
  namespace: {{ .Release.Namespace }}
  labels:
    app.kubernetes.io/name: {{ include "products-chart.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
