apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "cart.fullname" . }}-config
  namespace: {{ .Release.Namespace }}
data:
  LOG_LEVEL: {{ .Values.configMap.LOG_LEVEL | quote }}
  FEATURE_FLAG: {{ .Values.configMap.FEATURE_FLAG | quote }}
