apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "cart.fullname" . }}
  labels:
    {{- include "cart.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "cart.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "cart.selectorLabels" . | nindent 8 }}
    spec:
      imagePullSecrets:
        {{- toYaml .Values.imagePullSecrets | nindent 8 }}
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: http
              containerPort: 8081
              protocol: TCP
          env:
            - name: REDIS_URI
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.cartSecret.name }}
                  key: {{ .Values.cartSecret.redisKey }}
            - name: JWT_SECRET
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.cartSecret.name }}
                  key: {{ .Values.cartSecret.jwtKey }}
          envFrom:
            - configMapRef:
                name: {{ include "cart.fullname" . }}-config