apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.cartSecret.name }}
  namespace: {{ .Release.Namespace }}
  labels:
    app.kubernetes.io/name: {{ include "cart.name" . }}
    helm.sh/chart: {{ include "cart.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/version: {{ .Chart.AppVersion }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
type: Opaque
stringData:
  redisUri: {{ .Values.cartSecret.data.redisUri | quote }}
  jwtSecret: {{ .Values.cartSecret.data.jwtSecret | quote }}
