apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.cartSecret.name }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "cart.labels" . | nindent 4 }}
type: Opaque
stringData:
  redisUri: {{ .Values.cartSecret.redisUri | quote }}
  jwtSecret: {{ .Values.cartSecret.jwtSecret | quote }}
