{{- if .Values.serviceAccount -}}
{{- if .Values.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ .Values.serviceAccount.name | default (include "cart.fullname" .) }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "cart.labels" . | nindent 4 }}
automountServiceAccountToken: {{ .Values.serviceAccount.automount | default true }}
{{- end -}}
{{- end -}}