apiVersion: v1
kind: Service
metadata:
  name: {{ include "cart.fullname" . }}
  labels:
    app.kubernetes.io/name: "{{ include "cart.name" . }}"
    app.kubernetes.io/instance: "{{ .Release.Name }}"
    app.kubernetes.io/version: "{{ .Chart.AppVersion }}"
    helm.sh/chart: "{{ include "cart.chart" . }}"
    app.kubernetes.io/managed-by: "{{ .Release.Service }}"
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: 80
      protocol: TCP
      name: http
  selector:
    app.kubernetes.io/name: "{{ include "cart.name" . }}"
    app.kubernetes.io/instance: "{{ .Release.Name }}"
