apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.postgresqlSecret.name }}
  namespace: database
type: Opaque
data:
  {{ .Values.postgresqlSecret.usernameKey }}: {{ .Values.postgresql.username | b64enc }}
  {{ .Values.postgresqlSecret.passwordKey }}: {{ .Values.postgresql.password | b64enc }}
